config/routes.rb
Gomidashi::Application.routes.draw do

  resources :tweets
  resources :tasks
  resources :members

  root :to => 'contents#index'
  match "/auth/:provider/callback" => "sessions#create"
  match "/logout" => "sessions#destroy", :as => :logout
  match '/contents/roll/'
  match '/tasks/index/'

end

app/models/task.rb
class Task < ActiveRecord::Base
  before_save :task_baddate,
              :unless=> Proc.new {|t| t.when > Time.new.to_date}
  before_save :task_samename,
              :unless=> Proc.new {|t| t.who != t.for}

  private
  def task_baddate
    return false
  end

  def task_samename
    return false
  end
end

app/controllers/tasks_controller.rb
#encoding: UTF-8
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json

  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:tasks])

    respond_to do |format|
      if @task.save
        flash[:msg] = '相手にゴミ当番をお願いできたよ！'
        format.html { redirect_to :controller =>'contents',:action =>'index' }
        Twitter.update("@#{@task.for} さん、@#{@task.who} さんが、#{@task.when.strftime("%m月%d日")}のゴミ出しをお願いしているよ！")
      else
        flash[:msg] = '【エラー】自分を指定しているか、もしくは過去の日付を選んでいる恐れがあります。'
        format.html { redirect_to :controller =>'contents',:action =>'index'}
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:tasks])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])

    Twitter.update("@#{@task.who} さん、@#{@task.for} さんとの#{@task.when.strftime("%m月%d日")}のタスクが完了したよ！　おつかれさま！")
    @task.destroy
    respond_to do |format|
      flash[:msg] = 'タスクを1件完了しました'
      format.html { redirect_to :controller =>'contents',:action =>'index'}
    end
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :who %><br />
    <%= f.text_field :who %>
  </div>
  <div class="field">
    <%= f.label :for %><br />
    <%= f.text_field :for %>
  </div>
  <div class="field">
    <%= f.label :when %><br />
    <%= f.date_select :when %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Who</th>
    <th>For</th>
    <th>When</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.who %></td>
    <td><%= task.for %></td>
    <td><%= task.when %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Who:</b>
  <%= @task.who %>
</p>

<p>
  <b>For:</b>
  <%= @task.for %>
</p>

<p>
  <b>When:</b>
  <%= @task.when %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>